### ISSUE TITLE
Header and iOS 8 Auto-Layout

### ISSUE THREAD

**Issue by orkenstein** [DenHeadless/DTTableViewManager#16]
Can not make it work with iOS 8 SDK. Headers are permanently hidden by zero size. This line helps:
```objective-c
 self.tableView.sectionHeaderHeight = 20;
```

How I register Header:
```
  [self registerHeaderClass:[TRHeaderView class] forModelClass:[NSString class]];
```

**Comment by DenHeadless** [comment]
You need to set sectionHeaderHeight property, if you want to show section headers. Also, when there are  no section header models, UITableViewDatasource method tableView:heightForHeaderInSection will get CGFLOAT_MIN in return.

To set header models, you can use setSectionHeaderModels: method.

Is there a specific issue with autolayout in your setup? It's not clear from issue description.

**Comment by orkenstein** [comment]
Yep, looks like headers currently does not support auto size.
Thanks.
