### ISSUE TITLE
removeAllTableItems and animation

### ISSUE THREAD

**Issue by orkenstein** [DenHeadless/DTTableViewManager#18]
Is `[DTMemoryStorage removeAllTableItems]` animated?
In my case items get removed without animation. The similar code works correct:
```
 [self.memoryStorage removeItems:[[self.memoryStorage.sections[0] objects] copy]];

```

**Comment by DenHeadless** [comment]
Yes, this method simply calls reloadData after items are deleted.

I've added new method - removeAllTableItemsAnimated to address this issue. This is implemented in [3.0.5 release](https://github.com/DenHeadless/DTTableViewManager/releases/tag/3.0.5.)
