### ISSUE TITLE
`pod try` doesn't work

### ISSUE THREAD

**Issue by aaronbrethorst** [DenHeadless/DTTableViewManager#24]
It doesn't generate a working example project.

**Comment by DenHeadless** [comment]
That's true, i've switched to using Carthage for dependency management as it's simpler. 

I'll look into it, maybe i'll find a way to support pod try, for now you can clone project and run 

```
carthage update
```

in project directory. 
https://github.com/DenHeadless/DTTableViewManager#running-example-project

**Comment by DenHeadless** [comment]
Starting with 4.5.2 release, pod try is now supported.

Note, you need cocoapods at least at 1.0.0-beta2 version to successfully try DTTableViewManager.
