### ISSUE TITLE
Using Protocols as ModelType

### ISSUE THREAD

**Issue by fatuhoku** [DenHeadless/DTTableViewManager#26]
I'm working on a project where I actually use Protocols to represent my model objects rather than classes.  The main reason is that I use Parse subclasses to manage my data, and yet I do not want my View layer classes to know about Parse subclasses. Thus, Views talk to Model protocols (e.g. `Recipe`  protocol describes a recipe, whereas a `MESRecipe_Parse` `PFObject` subclass conforms to it).

I tried it, it doesn't look like `DTTableViewController` supports this because it fails to find the cell mapping.

```swift
class RecipeSearchResultCell: UITableViewCell, ModelTransfer {
    func updateWithModel(model: MESRecipe_Parse) {
        NSLog("Calling update with model.")
    }
}
```

What to do?

**Comment by DenHeadless** [comment]
Unfortunately, it's not easy to support protocols as data models. The reason being is that i use reflection API(MirrorType) to introspect, what model i receive. And that introspection will not be able to see protocol - it will see concrete type, that was passed in.

If it is possible to detect protocols via reflect method - i would be really happy to add this functionality, however i don't see how.

In the meantime, i can suggest several workarounds:
1. Use MVVM pattern and have a view model, that represents your PFObject. This view model can internally link to original PFObject and conform to your protocol
2. Conditionally cast your PFObject to one of your protocols.
3. Some other option i'm not seeing right now

It sounds like first option is one you are looking for - with MVVM your views will know only about view-model, they will not know it's actually backed up by PFObject and ParseSDK.

**Comment by DenHeadless** [comment]
@fatuhoku I'm happy to report that starting with [4.4.0 release](https://github.com/DenHeadless/DTTableViewManager/releases/tag/4.4.0), protocols are now accepted as data models. :beer:

**Comment by fatuhoku** [comment]
@DenHeadless W00T! Fantastic :) :beers:
I'll take another look at this in due course.
