### ISSUE TITLE
Add/remove/select example numbering inconsistency

### ISSUE THREAD

**Issue by devalfamac** [DenHeadless/DTTableViewManager#27]
Hi,

In example Add/remove/select, after removing, and adding some rows I got this result: 

(https://cloud.githubusercontent.com/assets/15522075/10863894/51f11056-7fdb-11e5-8d74-4fbd97500d03.png)

Rows numbers are repeated.

I don't now it's error in this example or in the framework.
Keep good work. Regards.

**Comment by devalfamac** [comment]
Sorry, I now realized that number of row is added from count of items, so this example is constructed is such way.

**Comment by DenHeadless** [comment]
No problem :beer:
