### ISSUE TITLE
Using Carthage can't import RealmStorage

### ISSUE THREAD

**Issue by ericlewis** [DenHeadless/DTTableViewManager#29]
Following the readme directions but RealmStorage isn't accessible. Everything else is. Integrating with existing project. But not bridging to objc. Only using in swift.

**Comment by ericlewis** [comment]
Module not found error.

**Comment by DenHeadless** [comment]
Sorry, did not quite get it, what module not found?

Did you add 

```swift
import DTTableViewManager
import DTModelStorage
```

to your swift file or bridging header?

**Comment by ericlewis** [comment]
No the problem is I'm not able to access RealmStorage from SWIFT. I'm not trying to use in objective c.

**Comment by DenHeadless** [comment]
And i'm talking about Swift, not ObjectiveC. ObjectiveC is not supported at all by DTTableViewManager.

**Comment by DenHeadless** [comment]
I'm closing issue until more info is provided. If you are still experiencing this problem, or have more information to share, please feel free to reopen.
