### ISSUE TITLE
When adding an item within whenSelected function, configureCell doesn't get called

### ISSUE THREAD

**Issue by augmentedworks** [DenHeadless/DTTableViewManager#33]
Hello!
If you add a new item on your memoryStorage within a whenSelected function, configureCell for the new cell doesn't get called.

For example:

`manager.registerCellClass(RightDetailTableViewCell.self) { [weak self] (cell, model, indexPath) -> Void in
            let someObject = SomeObject()
            try! manager.memoryStorage.addItem(someObject, toSection: 0)
        }`

`manager.configureCell(SomeCell.self) { (cell, model, indexPath) -> Void in
            print("This doesn't get called")
        }`

I discovered that calling performSelectorOnMainThread works, which is strange because what is inside the whenSelected function is already executed on the main thread.

`manager.registerCellClass(RightDetailTableViewCell.self) { [weak self] (cell, model, indexPath) -> Void in
            self?.performSelectorOnMainThread("addItem", withObject: userInfo, waitUntilDone: true)
        }`

`func addItem() {
            let someObject = SomeObject()
            try! manager.memoryStorage.addItem(someObject, toSection: 0)
}`

Thanks

**Comment by DenHeadless** [comment]
Mmm, that's strange, i tried making this in example project, and everything works correctly, configureCell does get called.

Can you provide example project or some more information to reproduce this behaviour?

**Comment by augmentedworks** [comment]
Sure, I'll try to strip down a sample project with the issue. Just give me a day or two and I'll set it up.
Maybe there's a particular condition for it to happen.
I'll update asap.

**Comment by augmentedworks** [comment]
Sorry Denis, I was working with an older version of the library.
The last one doesn't have the problem.
Thanks

**Comment by DenHeadless** [comment]
No problem :beer:
