### ISSUE TITLE
Problems when building with Xcode 7.3

### ISSUE THREAD

**Issue by Dschee** [DenHeadless/DTTableViewManager#36]
I just recently tried to integrate this to my project and this project didn't build correctly when integrating via Carthage. So I forked it and after opening the project I could see that it was lacking the correct inclusion of Carthage dependencies using [the suggested build script phase](https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos) method. This was also true for the DTModelStorage dependency which I explain in [this issue](https://github.com/DenHeadless/DTModelStorage/issues/10).

**Comment by DenHeadless** [comment]
Closing, discussion in https://github.com/DenHeadless/DTModelStorage/issues/10
