### ISSUE TITLE
Cell mapping is missing for model

### ISSUE THREAD

**Issue by seyhunak** [DenHeadless/DTTableViewManager#38]
Hello, 

I was getting following error.

` fatal error: Cell mapping is missing for model: Task(userId: 1, id: 1, title: "delectus aut autem", completed: false)
`
```
  {
    "id" : 199,
    "title" : "numquam repellendus a magnam",
    "userId" : 10,
    "completed" : true
  },
  {
    "id" : 200,
    "title" : "ipsam aperiam voluptates qui",
    "userId" : 10,
    "completed" : false
  }
]
```

Cell mapping is missing for model: Task(userId: 1, id: 1, title: "delectus aut autem", completed: false)
fatal error: Cell mapping is missing for model: Task(userId: 1, id: 1, title: "delectus aut autem", completed: false): file /Users/seyhunak/Projects/DemoTableViewManager/Pods/DTTableViewManager/Source/DTTableViewManager.swift, line 532

Here is the my implementation.

TaskViewController.swift

```
let json: NSArray? = try response.mapJSON() as? NSArray
   if let json = json {
       let tasks: Array<Task>? = Mapper<Task>().mapArray(json)
                        
       self.manager.memoryStorage.removeAllItems()
       self.manager.memoryStorage.addItems(tasks!, toSection: 0)
       self.tableView.reloadData()                        
}

```

Task.swift

```
import Foundation
import ObjectMapper

// MARK: Initializer and Properties

public struct Task: Mappable {
    
    var userId: Int!
    var id: Int!
    var title: String!
    var completed: Bool!

    // MARK: JSON
    
    public init?(_ map: Map) {
        mapping(map)
    }
    
    public mutating func mapping(map: Map) {
        userId <- map["userId"]
        id <- map["id"]
        title <- map["title"]
        completed <- map["completed"]
    }
    
}
```

Fyi @DenHeadless 

Thanks.

**Comment by DenHeadless** [comment]
Hey!

Prior to adding items to storage, you need to call

```
manager.registerCellClass(YourCellClass)
```

Where `YourCellClass` conforms to ModelTransfer protocol, therefore having following method:

```
class YourCellClass : UITableViewCell, ModelTransfer
{
    func updateWithModel(model: Task) {
    }
}
```

**Comment by Emptyless** [comment]
I have the same problem but I did define my cells to have the ModelTransfer and have the new Swift 3 syntax: 

`func update(with model: String) {
       self.nameLabel.text = model
        
    }`

Getting this exact error: 

> Error Domain=DTTableViewManager.DTTableViewFactoryError Code=1 "(null)"
fatal error: Cell mapping is missing for model: ["Test User 1", "Test User 2"]

**Comment by DenHeadless** [comment]
Your model for some reason is an Array of Strings, not String.

**Comment by Emptyless** [comment]
I have written a more detailed post on S.O. : [link](http://stackoverflow.com/questions/41580665/dttableviewmanager-cell-mapping-is-missing-for-model)

I am inputting an array of Strings in the `manager.memoryStorage.addItems(items)` like in the example right? What is/am I doing wrong?

**Comment by DenHeadless** [comment]
You should use `addItems` instead of `addItem` since you have an array of strings.

You would use `addItem` in case your model in cell is [String].

**Comment by Emptyless** [comment]
Thanks! I must have been reading over the 's' I did not have. Thank you very much.
