### ISSUE TITLE
Set height of cells

### ISSUE THREAD

**Issue by Dschee** [DenHeadless/DTTableViewManager#39]
How am I supposed to specify a cell height when using DTTableViewManager? I tried by adding my view controller as a `UITableViewDelegate` but then things like the `cellSelection` method callback didn't work any more as they seem to rely on delegation.

I guess that either there is not yet a possibility to do this or the README is lacking information that points out the correct direction. I might have missed it, of course, too. Could you clarify? Thanks for your help!

**Comment by DenHeadless** [comment]
Yes, sure.
While `DTTableViewManager` serves as `UITableViewDelegate`, it also trampolines all `UITableViewDelegate` methods to your controller( or any other `DTTableViewManageable` object). So basically you would just declare your view controller as `UITableViewDelegate`, and implement delegate methods normally. There's no need to actually set UITableView.delegate property, it's done automagically (tm)

There's mention about this behaviour in [README](https://github.com/DenHeadless/DTTableViewManager#uitableviewdelegate-and-uitableviewdatasource), however i agree that it could be expanded. I'll try to be more verbose about this point. Closing this for now, feel free to reopen or comment if you have any other questions.

**Comment by Dschee** [comment]
Thanks for the clarification, I'll try it out soon but now I understand what was meant when I read the README some time ago. 👍
