### ISSUE TITLE
Grouped table view's footer height

### ISSUE THREAD

**Issue by augmentedworks** [DenHeadless/DTTableViewManager#44]
Hello,

how can I set the footer height of a normal grouped table view? Since I can't use the table's delegate methods anymore and I don't want to set a view for a model, I cannot find a way to do it otherwise.

Thank you

**Comment by DenHeadless** [comment]
Hey, I don't really remember specifics of grouped table view footers, however you can use UITableView delegate methods to change height. Just extend your view controller(or whatever you use as UITableViewDelegate), and those methods will be called:

```swift
extension MyController : UITableViewDelegate {
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return CGFloat.leastNormalMagnitude
    }
}
```

Alternatively, you can also use new events system in DTTableViewManager 5:

```swift
manager.heightForFooter(withItem: String.self) { _ in 
    return 20
}
```

As you can see, i also used simple String instead of model, so that `UITableView` used `tableView(_:titleForFooterInSection:)` method instead of `tableView(_:viewForFooterInSection:)` method.

Hope this helps.

**Comment by DenHeadless** [comment]
Oh wow, there's actually a bug on master, where delegate methods for headers and footers are not called. I pushed a fix in ec810e71e9b02e15d355d0cec09471a4d3fb911a, can you try and tell me if it works for you?

**Comment by augmentedworks** [comment]
Hmm, I cannot make it work... I uploaded a sample project here if you want to take a look: https://github.com/augmentedworks/GroupedTest
Neither the table view delegate nor the heightForFooter methods are called.

The DTTableViewManager goes inside this if (line 925):

`        if configuration.sectionFooterStyle == .title`

Therefore it doesn't even reach the last return that you modified in the last commit.

**Comment by DenHeadless** [comment]
@augmentedworks Thanks for providing example project.

You need to set a model for section footer for this to work. Modify you example code to following:

```swift
        manager.memoryStorage.addItem("Woman", toSection: 1)
        
       // Add this line
        manager.memoryStorage.setSectionFooterModels([""])
        
        manager.heightForFooter(withItem: String.self) { (model, section) -> CGFloat in
            return 20
        }
```

This way event is getting called, and if you comment event code, delegate will get called as well.

**Comment by DenHeadless** [comment]
Oh wow, i misunderstood this for second time. It works for event, but does not work if you want to use UITableViewDelegate methods. 
We need to indeed call the delegate there, i'll prepare a fix for this.

**Comment by DenHeadless** [comment]
I pushed a fix, `UITableViewDelegate` is quieried immediately after events, and before we run a custom logic, that varies based on fact that storage may or may not have a model. So now both events for model, and even old plain delegate should work.

Please let me know if i'm being wrong for the third time =) Big thanks for bringing this up, great to fix such stuff around beta period, not in final release. :beers:

**Comment by augmentedworks** [comment]
It works great now!
Thanks a lot for your support and for improving this wonderful library! 🍻
