### ISSUE TITLE
How to use didUpdateContent

### ISSUE THREAD

**Issue by ericlewis** [DenHeadless/DTTableViewManager#45]
I have attempted to use the updater class including trying the setup from the tests but it never seems to be called. I have also tried to create my own and register it but it is the same result. Never seems to get called. Does anyone have working example code of this in action? 

EDIT: It does "work" but doesn't fire if the table has 0 content to be updated. I.E empty state as a result of no content that could be loaded. I think readme is incorrect

**Comment by DenHeadless** [comment]
Hey!
I think the reason for this might be that `UITableViewDataSource` methods are getting called earlier than TableViewUpdater is set. 
As a workaround, i can suggest you calling tableView.reloadData after you setup TableViewUpdater, or from viewWillAppear to trigger it when view appears on screen.

I am open to different solutions to this, if you have any.

**Comment by ericlewis** [comment]
I actually did try that and same result, but found a workaround in the meantime based on our network call.
