### ISSUE TITLE
iOS 10.2 

### ISSUE THREAD

**Issue by DBitros** [DenHeadless/DTTableViewManager#48]
With iOS 10.2 I see an issue with a delay on loading the table cells and also sometimes displaying the text and image I have in the cell don't load correctly either (usually occurs on one cell and the other cells display fine). Works fine on previous iOS versions. I've tried storageNeedsReloading() and reloadItem(item) to force a reload but to no avail.

**Comment by DenHeadless** [comment]
Hey!

That's interesting, we do not see this behavior currently in our apps. Do you have any specific details on when and why this happens? Also, which version are you using, Swift 2.3 or 3.0?

It would be great to have working sample of this bug, or maybe an Instruments trace.

**Comment by DBitros** [comment]
Thanks for the quick response. I believe I've misunderstood the problem. I had read through previous issues and realised that the problem was caused by not running manager.memoryStorage.addItem(someItem) on the main thread. I've done that now and it has fixed the issue.
