### ISSUE TITLE
Invoke custom action

### ISSUE THREAD

**Issue by flypaper0** [DenHeadless/DTTableViewManager#49]
How can I invoke in cell custom action? For example I have viewController with 
`func presentScreen() {
     let viewController = ViewController()
     present(viewController, animated: true, completion: nil)
}
`

and want to call this method on tap a button from cell

**Comment by DenHeadless** [comment]
You can subscribe to button tap for example in configureCell Event, something like this:

```swift
manager.configure(MyCell.self) { cell, model, indexPath in
   // subscribe for button tap
}
```

Remember that you need to unsubscribe in prepareForReuse or events will be duplicated. One useful pattern i found for myself is use RxSwift, subscribe to tap and make a DisposeBag, which disposes in `prepareForReuse` method, like so:

```swift
manager.configure(MyCell.self) { cell, model, indexPath in
     cell.button.rx.tap.asDriver().drive(onNext: { [weak self] in
        self?.presentScreen()
     }).disposed(by: cell.reuseDisposeBag)
}
```
