### ISSUE TITLE
How to listen changes of stored property? 

### ISSUE THREAD

**Issue by flypaper0** [DenHeadless/DTTableViewManager#50]
Hello! Good Job, I like your repo. But I have a question :) 

I have cell with UITextField and configure, it with default text. TextField from cell after editing change stored property in View Controller. When I scroll tableView down and up again textfield text setting to default `textFieldText` value. How to listen changes of `textFieldText`?

```
// stored property
var textFieldText = "TextField"
 
override func viewDidLoad() {
    super.viewDidLoad()

   // .. configurate manager
    manager.memoryStorage.addItem(textFieldText)
}

// cell
 func update(with model: String) {
     textField.text =  model
 }
```

**Comment by DenHeadless** [comment]
Hey!

The simplest would option is probably to use property observers, something like this:

```swift
var textFieldText = " foo" {
    didSet { manager.memoryStorage.setItems([newValue]) }
}
```
