### ISSUE TITLE
Override  tableView:sourceIndexPath:to: func 

### ISSUE THREAD

**Issue by DimaMishchenko** [DenHeadless/DTTableViewManager#51]
how i can override this func  ?
`func tableView(_ tableView: UITableView, moveRowAt sourceIndexPath: IndexPath, to destinationIndexPath: IndexPath) `

i need this to reorder items in database

**Comment by DenHeadless** [comment]
Right now you have 2 options:

1. Use default behaviour for MemoryStorage - if it suits you https://github.com/DenHeadless/DTTableViewManager/blob/master/Source/DTTableViewManager.swift#L809-L818 (in most cases it should).
1. Make yourself conform to `UITableViewDataSource` protocol and implement this method on `DTTableViewManageable` instance. Unfortunately, this will force you to implement other datasource methods, but you can redirect them to `DTTableViewManager` instance.

I will probably add 3 option as block event in the future, seems this method was missed when i was implementing other events. I will leave this issue open as a reminder, if you don't mind.

**Comment by DimaMishchenko** [comment]
ok, thank you for answer!

**Comment by DimaMishchenko** [comment]
please help me again, how to conform to `UITableViewDataSource` ?
i'm trying this:
`self.tableView.dataSource = self`
but it don't call dataSource functions
