### ISSUE TITLE
Cocoapods error

### ISSUE THREAD

**Issue by makleso6** [DenHeadless/DTTableViewManager#56]
Hi! Thanks for great lib!
I have issue with swift 4 and cocoa pods installation
[!] Unable to satisfy the following requirements:

- `DTTableViewManager (~> 6.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `DTTableViewManager (~> 6.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by DenHeadless** [comment]
Hey!
Currently 6.0.0 has not been released, it's in beta, but you can install latest beta release by specifying following in the Podfile:

```ruby
pod 'DTTableViewManager', '~> 6.0.0-beta.3'
```

**Comment by makleso6** [comment]
Thanks
