### ISSUE TITLE
Version 6.1.0-beta.1 is not compiled from original source files

### ISSUE THREAD

**Issue by iomark** [DenHeadless/DTTableViewManager#57]
![screen shot 2017-12-29 at 3 41 08 pm](https://user-images.githubusercontent.com/1295212/34438419-6968a350-ecaf-11e7-8462-1f343847d7ee.png)

**Comment by DenHeadless** [comment]
Hey!

It looks like you didn't run `carthage update` before compiling Example project. The mentioned API appeared in DTModelStorage 7.0.0-beta.1, on which DTTableViewManager 6.1.0-beta.1 depends on.
