### ISSUE TITLE
Wrong tableView section header width.

### ISSUE THREAD

**Issue by ihorodnikoff** [DenHeadless/DTTableViewManager#58]
Hey guys! 
I have some troubles with tableView header width only on devices iPhone 6+, 6s+ with iOS 9x.

The header is a UITableViewHeaderFooterView. 
The table view's style was set as "Grouped".

**Comment by DenHeadless** [comment]
Hey!

Can you describe problems in more detail? It does not look like framework is working with section headers width, the only thing we can sometimes modify is section header height.

**Comment by ihorodnikoff** [comment]
The problem was not in your framework. Thanks)
