### ISSUE TITLE
TableView doesn't update without animation after reloadData()

### ISSUE THREAD

**Issue by DimaMishchenko** [DenHeadless/DTTableViewManager#60]
After 6.1.0 release it doesn't updates after use `updateWithoutAnimations` block and call `reloadData()`. Same for the `DTCollectionView`. Check this please.

**Comment by DenHeadless** [comment]
This appears to be a bug in DTModelStorage. I pushed [7.0.1](https://github.com/DenHeadless/DTModelStorage/releases/tag/7.0.1) release with a fix. Please try it, and reopen the issue if for some reason it does not work. Thanks for reporting!
