### ISSUE TITLE
I'm a dummy, but how to set section header?

### ISSUE THREAD

**Issue by rablador** [DenHeadless/DTTableViewManager#61]
I have:

`SearchResultSectionHeader` - UIView with matching nib, implements ModelTransfer
`SearchResultSectionHeaderModel` - Model for the above

I've tried (in all combinations):

`manager.registerHeader(SearchResultSectionHeader.self)`
`manager.memoryStorage.setSectionHeaderModel(SearchResultSectionHeader.self, forSection: 0)`
`manager.memoryStorage.setSectionHeaderModel(SearchResultSectionHeaderModel.self, forSection: 0)`

Still can't see my custom section header view in the table. I have populated the table with cells. I must be doing something wrong, but what?

**Comment by yurikoles** [comment]
@rablador please use markdown syntax  for you code.

**Comment by DenHeadless** [comment]
Try setting header height to some non-zero value.

**Comment by rablador** [comment]
@DenHeadless No change.Current configuration is as follows

**SearchResultSectionHeader.swift**
```
class SearchResultSectionHeader: UITableViewHeaderFooterView: ModelTransfer {
    @IBOutlet private weak var title: UILabel!
    
    func update(with model: SearchResultSectionHeaderModel) {
        title.text = model.title
    }
}
```

**SearchResultSectionHeaderModel.swift**
```
class SearchResultSectionHeaderModel {
    var title: String!
}
```

**In view controller - viewDidLoad**
```
tableView.sectionHeaderHeight = 30
manager.registerHeader(SearchResultSectionHeader.self)
```

**Comment by DenHeadless** [comment]
And you should also set header model, for example like so:

```
manager.memoryStorage.setSectionHeaderModel(SearchResultsSectionHeaderModel(), forSection: 0)
```

**Comment by rablador** [comment]
Ah, I did not realise I have to set an actual model object! Well, problem solved. 👍
