### ISSUE TITLE
Add items without animation

### ISSUE THREAD

**Issue by mrJ0hn** [DenHeadless/DTTableViewManager#65]
Hello! Please, help me. I want to add items without animation. But I can't.

I tried to set up none animation
```
        let updater = TableViewUpdater(tableView: tableView)
        updater.insertRowAnimation = .none
        updater.reloadSectionAnimation = .none
        updater.reloadRowAnimation = .none
        manager.tableViewUpdater = updater
```
It doesn't work.

**Comment by DenHeadless** [comment]
Hi!

Assuming we are talking about `MemoryStorage`, there are several ways to make this happen, but i would say the most reliable of them would be something like this:

```swift
var items = manager.memoryStorage.items(inSection: 0) ?? []
items.append(contentsOf: [newItems])
manager.memoryStorage.setItems(items, forSection: 0)
```

Translating to UIKit API, this basically changes datasource for section 0, and calls `reloadData` on `UITableView`, so there would be no animation happening.

Alternatively, if you want to change multiple sections at once, you could modify sections directly, getting them from `manager.memoryStorage.section(at: 0) as? SectionModel`, and then calling `manager.memoryStorage.storageNeedsReloading()`, which again would call `UITableView.reloadData` method.

**Comment by mrJ0hn** [comment]
Many thanks!
